### ISSUE TITLE
Memory usage C++ vs Java and speed

### ISSUE THREAD

**Issue by LetterRip** [bupticybee/TexasSolver#6] opened 2021-08-07 06:41 UTC
Hi, you mention that the C++ version is slower for flop solves than the Java version.  Do they use similar amounts of memory?  Also roughly how much slower?

Thanks for really neat software to play with.

**Comment by LetterRip** [comment] 2021-08-09 21:22
Ah looks like you have posted this information elsewhere,

for those interested "c++ implement exact the same algorithm, it runs at least 3 times faster and requires at least 3 times smaller memory, but that's not enough . I'm current aggressively trying to optimize it to be even faster."

So definitely worth using the C++ version for those interested in speed and memory efficiency.

**Comment by bupticybee** [comment] 2021-08-11 08:28
Thats old information. I spend a lot of time optimize it, now the speed of cpp version is 5x at least and memory usage is even fewer than 1/3 of java version.

**Comment by bupticybee** [comment] 2021-09-01 03:47
Closing because the issue is considered solved.

**Comment by bupticybee** [comment] 2021-09-01 03:47
Closing because the issue is considered solved.

**Closed by bupticybee** 2021-09-01 03:47 UTC

**Comment by tankche1** [comment] 2022-08-27 00:36
> Closing because the issue is considered solved.

Can you explain a bit about the bottleneck of the speed?

I am considering build a python version. Do you think there will be a huge problem with speed?

**Comment by bupticybee** [comment] 2022-08-29 03:56
> @bupticybee Can you explain a bit about the bottleneck of the speed?
> 
> I am considering build a python version. Do you think there will be a huge problem with speed?

There will be huge problem using python, it's not a suitable language for solvers. I used to use python to build prototype of this solver, and eventually I translate everything to java, and then c++.
Python is NOT suitable for this job, if you use python, you will soon find everything is a bottleneck, interpreter, lack of type system, speed, memory, you name it.
